CI: test shared workflow experiment

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -10,73 +10,44 @@ on:
       - develop
 
 jobs:
-  deploy:
-    name: Running unit tests
-    runs-on: macos-15
+  setup:
+    uses: kukai-wallet/ios_shared_ci/.github/workflows/shared_setup.yml@main
+
+  process-setup:
+    needs: setup
+    runs-on: ${{ needs.setup.outputs.IOS_SHARED_SETUP_RUNS_ON }}
     steps:
-      - name: Select Xcode version
-        #run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'
-        run: sudo xcode-select -s '/Applications/Xcode_26.0.app/Contents/Developer'
-        
-      - name: Checkout repository
-        uses: actions/checkout@v4.1.1
-
-      - name: Get current date
-        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
-
-
-
-      # # Temporary step due to Xcode 15 / Github actions runner issues
-      # - name: Install iOS 16 simulator for Xcode 15
-      #   run: |
-      #     # Make iOS 16.4 simulator runtime available to Xcode 15
-      #     sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
-      #     sudo ln -s /Applications/Xcode_14.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 16.4.simruntime
-           
-      #     # Create an iOS 16.4 simulator
-      #     xcrun simctl create "iPhone 14 Pro (16.4)" "com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro" "com.apple.CoreSimulator.SimRuntime.iOS-16-4"
-      
-
-
-      # - name: Install yeetd
-      #   run: |
-      #     wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
-      #     sudo installer -pkg yeetd-normal.pkg -target /
-      #     yeetd &
-
-
-
-
-      # - name: Initialize CodeQL
-      #   uses: github/codeql-action/init@v3
-      #   with:
-      #     languages: "swift"
-      
-
-
-      # - name: Launch simulator
-      #   run: open -a Simulator --args -CurrentDeviceUDID $(xcrun simctl list --json | ruby -e "require 'json'; puts JSON.parse(ARGF.read)['devices']['com.apple.CoreSimulator.SimRuntime.iOS-17-0'].find { |s| s['name'] == 'iPhone 15' }['udid']")
-
-
-
 
       - name: Test
-        #run: xcodebuild test -scheme KukaiCoreSwift -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14" -enableCodeCoverage YES -resultBundlePath "~/xcode-$NOW.xcresult"
-        run: xcodebuild test -scheme KukaiCoreSwift -destination "platform=iOS Simulator,OS=26.0,name=iPhone 17" -enableCodeCoverage YES -resultBundlePath "~/xcode-$NOW.xcresult"
+        run: |
+          echo "IOS_SHARED_SETUP_RUNS_ON: ${{ needs.setup.outputs.IOS_SHARED_SETUP_RUNS_ON }}"
+          echo "IOS_SHARED_SETUP_RUNS_ON: ${{ needs.setup.outputs.IOS_SHARED_SETUP_XCODE_VERSION }}"
+          echo "IOS_SHARED_SETUP_RUNS_ON: ${{ needs.setup.outputs.IOS_SHARED_SETUP_SIMULATOR_VERSION }}"
 
 
 
-      # - name: Perform CodeQL Analysis
-      #   uses: github/codeql-action/analyze@v3
-      #   with:
-      #     category: "/language:swift"
-      
+  # test:
+  #   name: Running unit tests
+  #   runs-on: macos-15
+  #   steps:
+  #     - name: Select Xcode version
+  #       #run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'
+  #       run: sudo xcode-select -s '/Applications/Xcode_26.0.app/Contents/Developer'
+        
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4.1.1
 
+  #     - name: Get current date
+  #       run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
 
-      - name: Upload results
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v4.3.1
-        with:
-          name: "results-${{ env.NOW }}.xcresult"
-          path: "~/xcode-${{ env.NOW }}.xcresult"
+  #     - name: Test
+  #       #run: xcodebuild test -scheme KukaiCoreSwift -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14" -enableCodeCoverage YES -resultBundlePath "~/xcode-$NOW.xcresult"
+  #       run: xcodebuild test -scheme KukaiCoreSwift -destination "platform=iOS Simulator,OS=26.0,name=iPhone 17" -enableCodeCoverage YES -resultBundlePath "~/xcode-$NOW.xcresult"
+
+  #     - name: Upload results
+  #       if: ${{ success() || failure() }}
+  #       uses: actions/upload-artifact@v4.3.1
+  #       with:
+  #         name: "results-${{ env.NOW }}.xcresult"
+  #         path: "~/xcode-${{ env.NOW }}.xcresult"
       
